### ISSUE TITLE
Won't run on arch, fresh install

### ISSUE THREAD

**Issue by matt-seaton** [binhex/moviegrabber#6]
Traceback (most recent call last):
  File "MovieGrabber.py", line 6754, in <module>
    while host_ip() == 0:
  File "MovieGrabber.py", line 895, in host_ip
    network_info = socket.getaddrinfo(socket.gethostname(), None)
socket.gaierror: [Errno -2] Name or service not known

**Comment by matt-seaton** [comment]
Now it works suddenly.  I don't get computers.
